/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import static Project.LoginAndRegister.genUserID;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class LoginAndRegister extends javax.swing.JFrame {

    protected static int userId;
    protected static String userName;

    /**
     * Creates new form LoginAndRegister
     */
    public LoginAndRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        line = new javax.swing.JPanel();
        kmutt = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lb_register = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        lb_password = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        line2 = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        username_rt = new javax.swing.JTextField();
        studentID_rt = new javax.swing.JTextField();
        lb_password_rt = new javax.swing.JLabel();
        password_rt = new javax.swing.JPasswordField();
        lb_confirmPassword_rt = new javax.swing.JLabel();
        confirmPassword_rt = new javax.swing.JPasswordField();
        pic_username = new javax.swing.JLabel();
        pic_password = new javax.swing.JLabel();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setBackground(new java.awt.Color(255, 102, 0));
        panelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line.setBackground(new java.awt.Color(255, 255, 255));
        line.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        panelBG.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 80, 3, 360));

        kmutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/kmutt1.png"))); // NOI18N
        panelBG.add(kmutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        username.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText(" Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        panelBG.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 180, 40));

        lb_register.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        lb_register.setForeground(new java.awt.Color(255, 255, 255));
        lb_register.setText("Sign Up");
        panelBG.add(lb_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        login.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 102, 0));
        login.setText("Sign In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        panelBG.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 90, 30));

        lb_password.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_password.setForeground(new java.awt.Color(204, 204, 204));
        lb_password.setText("Password");
        panelBG.add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        password.setForeground(new java.awt.Color(204, 204, 204));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        panelBG.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 180, 40));

        line2.setBackground(new java.awt.Color(204, 204, 204));
        line2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBG.add(line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 138, 390, 4));

        register.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 102, 0));
        register.setText("Sign Up");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        panelBG.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 90, 30));

        username_rt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        username_rt.setForeground(new java.awt.Color(204, 204, 204));
        username_rt.setText(" Username");
        username_rt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_rtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_rtFocusLost(evt);
            }
        });
        panelBG.add(username_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 180, 40));

        studentID_rt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        studentID_rt.setForeground(new java.awt.Color(204, 204, 204));
        studentID_rt.setText(" StudentID");
        studentID_rt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentID_rtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentID_rtFocusLost(evt);
            }
        });
        panelBG.add(studentID_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 180, 40));

        lb_password_rt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_password_rt.setForeground(new java.awt.Color(204, 204, 204));
        lb_password_rt.setText("Password");
        panelBG.add(lb_password_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        password_rt.setForeground(new java.awt.Color(204, 204, 204));
        password_rt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_rtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_rtFocusLost(evt);
            }
        });
        panelBG.add(password_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 40));

        lb_confirmPassword_rt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_confirmPassword_rt.setForeground(new java.awt.Color(204, 204, 204));
        lb_confirmPassword_rt.setText("Password");
        panelBG.add(lb_confirmPassword_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        confirmPassword_rt.setForeground(new java.awt.Color(204, 204, 204));
        confirmPassword_rt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassword_rtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPassword_rtFocusLost(evt);
            }
        });
        panelBG.add(confirmPassword_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 180, 40));

        pic_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/user-silhouette.png"))); // NOI18N
        panelBG.add(pic_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 40, 60));

        pic_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/locked-padlock.png"))); // NOI18N
        panelBG.add(pic_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        home.setBackground(new java.awt.Color(255, 102, 0));
        home.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        panelBG.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBG, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try {
            con = Database.getConnection();
            Statement stm = con.createStatement();
            String sql = "select user_pass from user where username =" + "'" + username.getText() + "'";
            ResultSet rs = stm.executeQuery(sql);
            userName = username.getText();
            if (rs.next()) {
                String passFromDatabase = rs.getString("user_pass");
                if (password.getText().equals(passFromDatabase)) {
                    String sqlUserId = "select userID from user where username =" + "'" + userName + "'";
                    ResultSet rsUserId = stm.executeQuery(sqlUserId);
                    if (rsUserId.next()) {
                        userId = rsUserId.getInt("userID");
                    }
                    System.out.println(userId);
                    HomeShowPostList home = new HomeShowPostList();
                    home.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "username หรือ password ไม่ถูกต้อง");
                }
            } else {
                JOptionPane.showMessageDialog(null, "username หรือ password ไม่ถูกต้อง");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_loginActionPerformed

    public static int genUserID() throws SQLException {
        Connection con = null;
        int x = 1;

        try {
            con = Database.getConnection();
            String sql = "select MAX(userID) FROM user";
            PreparedStatement pstm = con.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            if (rs.next()) {
                x = rs.getInt("max(userID)");
                x++;
            } else {
                x = 1;
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        return x;
    }


    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try {
            con = Database.getConnection();
            String sql = "insert into user (userID ,username,user_pass,student_ID) values (?,?,?,?)";
            PreparedStatement pstm = con.prepareStatement(sql);
            int number = genUserID();
            pstm.setInt(1, number);
            pstm.setString(2, username_rt.getText());
            pstm.setString(3, password_rt.getText());
            pstm.setString(4, studentID_rt.getText());

            System.out.println(number);
            System.out.println(username_rt.getText());
            System.out.println(password_rt.getText());
            System.out.println(studentID_rt.getText());

            if ((confirmPassword_rt.getText()).equals(password_rt.getText())) {
                int rs = pstm.executeUpdate();
                JOptionPane.showMessageDialog(null, "สมัครสมาชิกเรียบร้อย");
            } else {
                JOptionPane.showMessageDialog(null, "Your password not match");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_registerActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        lb_password.setVisible(false);
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if (!password.getText().equals("")) {
            lb_password.setVisible(false);
        } else {
            lb_password.setVisible(true);
        }
    }//GEN-LAST:event_passwordFocusLost

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if (username.getText().equals(" Username")) {
            username.setText("");
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if (username.getText().equals("")) {
            username.setText(" Username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void studentID_rtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentID_rtFocusGained
        // TODO add your handling code here:
        if (studentID_rt.getText().equals(" StudentID")) {
            studentID_rt.setText("");
        }
    }//GEN-LAST:event_studentID_rtFocusGained

    private void studentID_rtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentID_rtFocusLost
        // TODO add your handling code here:
        if (studentID_rt.getText().equals("")) {
            studentID_rt.setText(" StudentID");
        }
    }//GEN-LAST:event_studentID_rtFocusLost

    private void username_rtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_rtFocusGained
        // TODO add your handling code here:
        if (username_rt.getText().equals(" Username")) {
            username_rt.setText("");
        }
    }//GEN-LAST:event_username_rtFocusGained

    private void username_rtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_rtFocusLost
        // TODO add your handling code here:
        if (username_rt.getText().equals("")) {
            username_rt.setText(" Username");
        }
    }//GEN-LAST:event_username_rtFocusLost

    private void password_rtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_rtFocusGained
        // TODO add your handling code here:
        lb_password_rt.setVisible(false);
    }//GEN-LAST:event_password_rtFocusGained

    private void password_rtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_rtFocusLost
        // TODO add your handling code here:
        if (!password_rt.getText().equals("")) {
            lb_password_rt.setVisible(false);
        } else {
            lb_password_rt.setVisible(true);
        }
    }//GEN-LAST:event_password_rtFocusLost

    private void confirmPassword_rtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassword_rtFocusGained
        // TODO add your handling code here:
        lb_confirmPassword_rt.setVisible(false);
    }//GEN-LAST:event_confirmPassword_rtFocusGained

    private void confirmPassword_rtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassword_rtFocusLost
        // TODO add your handling code here:
        if (!confirmPassword_rt.getText().equals("")) {
            lb_confirmPassword_rt.setVisible(false);
        } else {
            lb_confirmPassword_rt.setVisible(true);
        }
    }//GEN-LAST:event_confirmPassword_rtFocusLost

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        HomeShowPostListNotLogin home = new HomeShowPostListNotLogin();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAndRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassword_rt;
    private javax.swing.JButton home;
    private javax.swing.JLabel kmutt;
    private javax.swing.JLabel lb_confirmPassword_rt;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_password_rt;
    private javax.swing.JLabel lb_register;
    private javax.swing.JPanel line;
    private javax.swing.JPanel line2;
    private javax.swing.JButton login;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password_rt;
    private javax.swing.JLabel pic_password;
    private javax.swing.JLabel pic_username;
    private javax.swing.JButton register;
    private javax.swing.JTextField studentID_rt;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username_rt;
    // End of variables declaration//GEN-END:variables
}
