/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import Project.Database;
import Project.Database;
import Project.LoginAndRegister;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
//import java.util.logging.Logger;  
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import java.sql.Date;

/**
 *
 * @author admin
 */
public class Post extends javax.swing.JFrame {

    protected static String getTField = "";
    protected static String getTArea = "";

    /**
     * Creates new form Post
     */
    public Post() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new javax.swing.JPanel();
        panelBar = new javax.swing.JPanel();
        kmutt = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        addTopic1 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        lb_kmutt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cancle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        topic = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setBackground(new java.awt.Color(255, 255, 255));
        panelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBar.setBackground(new java.awt.Color(255, 102, 0));
        panelBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kmutt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kmutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/kmutt1.png"))); // NOI18N
        panelBar.add(kmutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 100));

        home.setBackground(new java.awt.Color(255, 102, 0));
        home.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        panelBar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 150, 40));

        addTopic1.setBackground(new java.awt.Color(255, 255, 255));
        addTopic1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addTopic1.setForeground(new java.awt.Color(255, 102, 0));
        addTopic1.setText("ADD TOPIC");
        panelBar.add(addTopic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 250, 150, 40));

        profile.setBackground(new java.awt.Color(255, 102, 0));
        profile.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("PROFILE");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        panelBar.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 150, 40));

        panelBG.add(panelBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 530));

        lb_kmutt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_kmutt.setForeground(new java.awt.Color(255, 102, 0));
        lb_kmutt.setText("King Mongkut's University of Technology Thonburi ");
        panelBG.add(lb_kmutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Add Post");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/add.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panelBG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 770, 60));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 2147480000));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 780, 2));

        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        panelBG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 450, 240));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Content :");
        panelBG.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, -1));

        cancle.setBackground(new java.awt.Color(204, 204, 204));
        cancle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cancle.setForeground(new java.awt.Color(255, 102, 0));
        cancle.setText("Cancle");
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });
        panelBG.add(cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Topic : ");
        panelBG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        panelBG.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 450, 40));

        submit.setBackground(new java.awt.Color(255, 102, 0));
        submit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Enter");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        panelBG.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 90, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Wecome");
        panelBG.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 60, 30));

        logout.setBackground(new java.awt.Color(255, 102, 0));
        logout.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        panelBG.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
        HomeShowPostList home = new HomeShowPostList();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancleActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        Profile pf = new Profile();
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profileActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        Connection con = Database.getConnection();
        try {
            String sql = "insert into Post(postID,post_name,post_description,post_createDate,voteScore,post_editDate,isPin,userID) values (?,?,?,?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(sql);
            int postId = genId();
            int voteS = genVote();
            Date timedate = new Date();
            Timestamp tm = new Timestamp(timedate.getTime());
            stm.setInt(1, postId);
            stm.setString(2, topic.getText());
            stm.setString(3, content.getText());
            stm.setTimestamp(4, tm);
            stm.setInt(5, voteS);
            stm.setTimestamp(6, tm);
            stm.setBoolean(7, false);
            stm.setInt(8, LoginAndRegister.userId);
            int data = stm.executeUpdate();
//            getTField = topic.getText();
//            getTArea = content.getText();

            JOptionPane.showMessageDialog(null, "ตั้งกระทู้เรียบร้อย");
            PostShow pS = new PostShow();
            pS.setVisible(true);
            String sqlPostTop = "select max(post_name) from Post where userID =" + "'" + LoginAndRegister.userId + "'";
            String sqlPostCon = "select max(post_description) from Post where userID =" + "'" + LoginAndRegister.userId + "'";
            Statement stmTop = con.createStatement();
            Statement stmCon = con.createStatement();
            ResultSet rsPostTop = stmTop.executeQuery(sqlPostTop);
            ResultSet rsPostCon = stmCon.executeQuery(sqlPostCon);
            if (rsPostTop.next()) {
                getTField = rsPostTop.getString("max(post_name)");
            }
            if (rsPostCon.next()) {
                    getTArea = rsPostCon.getString("max(post_description)");
                }
                System.out.println(getTField + "    " + getTArea);

            
            this.setVisible(false);

        } catch (Exception e) {
            System.out.println(e);
        }
        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        HomeShowPostListNotLogin home = new HomeShowPostListNotLogin();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        HomeShowPostList home = new HomeShowPostList();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    public static int genId() throws SQLException {
        int count = 1;
        Connection con = Database.getConnection();
        Statement stm = con.createStatement();
        String sql = "select max(postId) from Post";
        ResultSet rs = stm.executeQuery(sql);
        if (rs.next()) {
            count = rs.getInt("max(postId)");
            count++;
        } else {
            count = 1;
        }

        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        return count;
    }

    public static int genVote() throws SQLException {
        int countVote = 1;
        Connection con = Database.getConnection();
        Statement stm = con.createStatement();
        String sql = "select voteScore from Post";
        ResultSet rs = stm.executeQuery(sql);
        if (rs.next()) {
            countVote = rs.getInt("voteScore");
            countVote++;
        } else {
            countVote = 1;
        }
        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        return countVote;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Post().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTopic1;
    private javax.swing.JButton cancle;
    private javax.swing.JTextArea content;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kmutt;
    private javax.swing.JLabel lb_kmutt;
    private javax.swing.JButton logout;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPanel panelBar;
    private javax.swing.JButton profile;
    private javax.swing.JButton submit;
    private javax.swing.JTextField topic;
    // End of variables declaration//GEN-END:variables
}
