/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import Project.Database;
import Project.Database;
import Project.LoginAndRegister;
import static Project.comment.genCommentID;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
//import java.util.logging.Logger;  
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import java.sql.Date;

/**
 *
 * @author admin
 */
public class Post1 extends javax.swing.JFrame {

    protected static String getTField = "";
    protected static String getTArea = "";
    protected static String postName = "";
    protected static String postCon = "";

    /**
     * Creates new form Post
     */
    public Post1() {
        initComponents();
        Ps1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Post = new javax.swing.JPanel();
        panelBar = new javax.swing.JPanel();
        kmutt = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        addTopic1 = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        lb_kmutt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cancle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        topic = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Ps1 = new javax.swing.JPanel();
        panelBar2 = new javax.swing.JPanel();
        kmutt3 = new javax.swing.JLabel();
        home3 = new javax.swing.JButton();
        addTopic3 = new javax.swing.JButton();
        profile2 = new javax.swing.JButton();
        lb_kmutt2 = new javax.swing.JLabel();
        nav1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        line4 = new javax.swing.JPanel();
        logout2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        showPostList1 = new javax.swing.JPanel();
        PostShow1 = new javax.swing.JPanel();
        postShow1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textComment1 = new javax.swing.JTextArea();
        lb_user2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 530));
        setResizable(false);

        Post.setBackground(new java.awt.Color(255, 255, 255));
        Post.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBar.setBackground(new java.awt.Color(255, 102, 0));
        panelBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kmutt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kmutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/kmutt1.png"))); // NOI18N
        panelBar.add(kmutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 100));

        home.setBackground(new java.awt.Color(255, 102, 0));
        home.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        panelBar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 150, 40));

        addTopic1.setBackground(new java.awt.Color(255, 255, 255));
        addTopic1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addTopic1.setForeground(new java.awt.Color(255, 102, 0));
        addTopic1.setText("ADD TOPIC");
        addTopic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTopic1ActionPerformed(evt);
            }
        });
        panelBar.add(addTopic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 250, 150, 40));

        profile.setBackground(new java.awt.Color(255, 102, 0));
        profile.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("PROFILE");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        panelBar.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 150, 40));

        Post.add(panelBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 530));

        lb_kmutt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_kmutt.setForeground(new java.awt.Color(255, 102, 0));
        lb_kmutt.setText("King Mongkut's University of Technology Thonburi ");
        Post.add(lb_kmutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Post.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Add Post");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/add.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Post.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 770, 60));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 2147480000));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Post.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 780, 2));

        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        Post.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 450, 240));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Content :");
        Post.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, -1));

        cancle.setBackground(new java.awt.Color(204, 204, 204));
        cancle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cancle.setForeground(new java.awt.Color(255, 102, 0));
        cancle.setText("Cancle");
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });
        Post.add(cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Topic : ");
        Post.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        Post.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 450, 40));

        submit.setBackground(new java.awt.Color(255, 102, 0));
        submit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Enter");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        Post.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 90, -1));

        logout.setBackground(new java.awt.Color(255, 102, 0));
        logout.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        Post.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 80, -1));

        Ps1.setBackground(new java.awt.Color(255, 255, 255));
        Ps1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBar2.setBackground(new java.awt.Color(255, 102, 0));
        panelBar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kmutt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kmutt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/kmutt1.png"))); // NOI18N
        panelBar2.add(kmutt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 100));

        home3.setBackground(new java.awt.Color(255, 102, 0));
        home3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        home3.setForeground(new java.awt.Color(255, 255, 255));
        home3.setText("HOME");
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });
        panelBar2.add(home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 150, 40));

        addTopic3.setBackground(new java.awt.Color(255, 102, 0));
        addTopic3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addTopic3.setForeground(new java.awt.Color(255, 255, 255));
        addTopic3.setText("ADD TOPIC");
        addTopic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTopic3ActionPerformed(evt);
            }
        });
        panelBar2.add(addTopic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 250, 150, 40));

        profile2.setBackground(new java.awt.Color(255, 102, 0));
        profile2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        profile2.setForeground(new java.awt.Color(255, 255, 255));
        profile2.setText("PROFILE");
        profile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile2ActionPerformed(evt);
            }
        });
        panelBar2.add(profile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 150, 40));

        Ps1.add(panelBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 530));

        lb_kmutt2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_kmutt2.setForeground(new java.awt.Color(255, 102, 0));
        lb_kmutt2.setText("King Mongkut's University of Technology Thonburi ");
        Ps1.add(lb_kmutt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 40));

        nav1.setBackground(new java.awt.Color(204, 204, 204));
        nav1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setText("Post");
        nav1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/open-book.png"))); // NOI18N
        nav1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Ps1.add(nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 770, 60));

        line4.setBackground(new java.awt.Color(255, 102, 0));
        line4.setMaximumSize(new java.awt.Dimension(2147483647, 2147480000));
        line4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Ps1.add(line4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 780, 2));

        logout2.setBackground(new java.awt.Color(255, 102, 0));
        logout2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        logout2.setForeground(new java.awt.Color(255, 255, 255));
        logout2.setText("Log Out");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        Ps1.add(logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 80, -1));

        jScrollPane4.setBorder(null);

        showPostList1.setBackground(new java.awt.Color(255, 255, 255));
        showPostList1.setForeground(new java.awt.Color(255, 255, 255));

        PostShow1.setBackground(new java.awt.Color(153, 153, 153));
        PostShow1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        postShow1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout PostShow1Layout = new javax.swing.GroupLayout(PostShow1);
        PostShow1.setLayout(PostShow1Layout);
        PostShow1Layout.setHorizontalGroup(
            PostShow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PostShow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(postShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PostShow1Layout.setVerticalGroup(
            PostShow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PostShow1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(postShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton2.setText("Comment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textComment1.setColumns(20);
        textComment1.setRows(5);
        jScrollPane5.setViewportView(textComment1);

        javax.swing.GroupLayout showPostList1Layout = new javax.swing.GroupLayout(showPostList1);
        showPostList1.setLayout(showPostList1Layout);
        showPostList1Layout.setHorizontalGroup(
            showPostList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showPostList1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(showPostList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PostShow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(showPostList1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(showPostList1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButton2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        showPostList1Layout.setVerticalGroup(
            showPostList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showPostList1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PostShow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(showPostList1);

        Ps1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 770, 390));

        lb_user2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_user2.setForeground(new java.awt.Color(206, 206, 206));
        lb_user2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Ps1.add(lb_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Post, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Post, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cancleActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
      
    }//GEN-LAST:event_profileActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        Connection con = Database.getConnection();
        try {
            String sql = "insert into Post(postID,post_name,post_description,post_createDate,voteScore,post_editDate,isPin,userID) values (?,?,?,?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(sql);
            int postId = genId();
            int voteS = genVote();
            Date timedate = new Date();
            Timestamp tm = new Timestamp(timedate.getTime());
            stm.setInt(1, postId);
            stm.setString(2, topic.getText());
            stm.setString(3, content.getText());
            stm.setTimestamp(4, tm);
            stm.setInt(5, voteS);
            stm.setTimestamp(6, tm);
            stm.setBoolean(7, false);
            stm.setInt(8, LoginAndRegister.userId);
            int data = stm.executeUpdate();
//            getTField = topic.getText();
//            getTArea = content.getText();

            
            String sqlPostNow = "select max(postID) from Post where userID =" + "'" + LoginAndRegister.userId + "'";
            Statement stmNow = con.createStatement();
            ResultSet rsPostNow = stmNow.executeQuery(sqlPostNow);
            if (rsPostNow.next()){
                getTField = rsPostNow.getString("max(postID)");
                System.out.println(getTField);
                String sqlPostTopic = "select post_name from Post where postID =" + "'" +getTField+"'";
                String sqlPostCon = "select post_description from Post where postID =" + "'" +getTField+"'";
                ResultSet rsPostTopic = stmNow.executeQuery(sqlPostTopic);
               
                if(rsPostTopic.next()){
                    postName=rsPostTopic.getString("post_name");
                    System.out.println(postName);
                }  
                ResultSet rsPostCon = stmNow.executeQuery(sqlPostCon);
                if(rsPostCon.next()){
                    postCon=rsPostCon.getString("post_description");
                    System.out.println(postCon);
                }
                
            }
           
            JOptionPane.showMessageDialog(null, "ตั้งกระทู้เรียบร้อย");
            Ps1.setVisible(true);
            postShow1.setText(postShow1.getText()+postName+"\n"+postCon);
            Post.setVisible(false);

        } catch (Exception e) {
            System.out.println(e);
        }
        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_logoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_homeActionPerformed

    private void addTopic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTopic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTopic1ActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home3ActionPerformed

    private void addTopic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTopic3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTopic3ActionPerformed

    private void profile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile2ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        try {
            con = Database.getConnection();

            String sql = "insert into Comment (commentID,comment_description,comment_date,postID,userID) values (?,?,?,?,?)";
            PreparedStatement psm = con.prepareStatement(sql);
            int num = genCommentID();
            Date timedate = new Date();
            Timestamp tm = new Timestamp(timedate.getTime());

            psm.setInt(1, num);
            psm.setString(2, textComment1.getText());
            psm.setTimestamp(3, tm);
            psm.setInt(4, 1);
            //String sql2 = "Select user.userID FROM user INNER JOIN Comment ON user.userID = Comment.userID";

            psm.setInt(5, 2);

            int x = psm.executeUpdate();

            System.out.println(genCommentID());
            System.out.println(textComment1.getText());
            System.out.println(tm);

        } catch (Exception e) {
            System.out.println("!!!!!!!!" + e);

        }
        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(null, "คอมเมนต์เรียบร้อยแล้ว");
    }//GEN-LAST:event_jButton2ActionPerformed

    public static int genId() throws SQLException {
        int count = 1;
        Connection con = Database.getConnection();
        Statement stm = con.createStatement();
        String sql = "select max(postId) from Post";
        ResultSet rs = stm.executeQuery(sql);
        if (rs.next()) {
            count = rs.getInt("max(postId)");
            count++;
        } else {
            count = 1;
        }

        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        return count;
    }

    public static int genVote() throws SQLException {
        int countVote = 1;
        Connection con = Database.getConnection();
        Statement stm = con.createStatement();
        String sql = "select voteScore from Post";
        ResultSet rs = stm.executeQuery(sql);
        if (rs.next()) {
            countVote = rs.getInt("voteScore");
            countVote++;
        } else {
            countVote = 1;
        }
        try {
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        return countVote;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Post1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Post1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Post1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Post1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Post1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Post;
    protected static javax.swing.JPanel PostShow1;
    private javax.swing.JPanel Ps1;
    private javax.swing.JButton addTopic1;
    private javax.swing.JButton addTopic3;
    private javax.swing.JButton cancle;
    private javax.swing.JTextArea content;
    private javax.swing.JButton home;
    private javax.swing.JButton home3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel kmutt;
    private javax.swing.JLabel kmutt3;
    private javax.swing.JLabel lb_kmutt;
    private javax.swing.JLabel lb_kmutt2;
    public static javax.swing.JLabel lb_user2;
    private javax.swing.JPanel line4;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout2;
    private javax.swing.JPanel nav1;
    private javax.swing.JPanel panelBar;
    private javax.swing.JPanel panelBar2;
    private javax.swing.JLabel postShow1;
    private javax.swing.JButton profile;
    private javax.swing.JButton profile2;
    private javax.swing.JPanel showPostList1;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea textComment1;
    private javax.swing.JTextField topic;
    // End of variables declaration//GEN-END:variables

    void setTopic(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setWriter(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setDate(int aInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
